from typing import TypedDict


ValidatorsQuery = TypedDict(
    'ValidatorsQuery',
    {
        'page': int,
        'limit': int,
        'offset': int,
        'address': str,
        'attributes': str,
        'blocks.last.hash': str,
        'blocks.last.number': int,
        'blocks.produced': int,
        'forged.fees': int,
        'forged.fees.from': int,
        'forged.fees.to': int,
        'forged.rewards': int,
        'forged.rewards.from': int,
        'forged.rewards.to': int,
        'forged.total': int,
        'forged.total.from': int,
        'forged.total.to': int,
        'isResigned': bool,
        'production.approval': int,
        'production.approval.from': int,
        'production.approval.to': int,
        'publicKey': str,
        'rank': int,
        'rank.from': int,
        'rank.to': int,
        'username': str,
        'votes': int,
        'votes.from': int,
        'votes.to': int,
        'orderBy': str,
    },
    total=False,
)
